- name: Clone xfce-panel configuration into home
  ansible.builtin.git:
    repo: 'git@github.com:deepeeess/xfce4-panel.git'
    dest: ~/xfce4-panel
    force: no
    update: no

- stat:
    path: ~/.config/xfce4/panel
  register: panel

- name: remove the panel directory (only if it is a folder)
  file:
    path: ~/.config/xfce4/panel
    state: absent
  when: panel.stat.isdir is defined and panel.stat.isdir

- name: ~/xfce4-panel
  file:
    src: "~/xfce4-panel"
    dest: ~/.config/xfce4/panel
    state: link
    force: yes
