- name: make sure  ~/.config/Code - OSS/User/ exists
  file:
    path: ~/.config/Code - OSS/User/
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0700

- name: make sure  ~/.config/Code/User/ exists
  file:
    path: ~/.config/Code/User/
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0700


- name: ~/.config/Code - OSS/User/settings.json
  file:
    src: "{{dotfiles_dir}}/files/visual-studio-code-settings.json"
    dest: ~/.config/Code - OSS/User/settings.json
    state: link
    force: yes

- name: ~/.config/Code/User/settings.json
  file:
    src: "{{dotfiles_dir}}/files/visual-studio-code-settings.json"
    dest: ~/.config/Code/User/settings.json
    state: link
    force: yes

- name: ~/.xinitrc
  file:
    src: "{{dotfiles_dir}}/files/xinitrc"
    dest: ~/.xinitrc
    state: link
    force: yes

- name: ~/.Xresources
  file:
    src: "{{dotfiles_dir}}/files/Xresources"
    dest: ~/.Xresources
    state: link
    force: yes

- name: make sure  ~/.xmonad exists
  file:
    path: ~/.xmonad
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0700

- name: ~/.xmonad/
  file:
    src: "{{dotfiles_dir}}/files/xmonad.hs"
    dest: ~/.xmonad/xmonad.hs
    state: link
    force: yes

- name: ~/.xmobarrc
  file:
    src: "{{dotfiles_dir}}/files/xmobarrc.hs"
    dest: ~/.xmobarrc
    state: link
    force: yes
