- name: xorg packages
  community.general.pacman: name={{ item }} state=present
  with_items:
    - autocutsel
    - chromium
    - code
    - firefox
    - gimp
    - glib2
    - rdesktop
    - xclip
    - xdotool
    - xfce4
    - xfce4-terminal
    - xmobar
    - xmonad
    - xmonad-contrib
    - xorg-appres
    - xorg-server
    - xorg-xfd
    - xorg-xfontsel
    - xorg-xlsfonts
    - xorg-xinput
    - xorg-xkill
    - xorg-xmessage # for displaying xmonad build issues when recompiling using Mod+q
    - xorg-xmodmap
    - xorg-xprop
    - xorg-xrdb
    - xorg-xwininfo
    - xterm
