
- name: openssl
  community.general.pacman:
    name: openssl
    state: latest

- name: ca-certificates
  community.general.pacman:
    name: ca-certificates
    state: latest

- name: reflector - install
  community.general.pacman:
    name: reflector
    state: present

- name: reflector - run
  ansible.builtin.command:  reflector --verbose --latest 5 --protocol https --protocol http --sort rate --save /etc/pacman.d/mirrorlist
