- name: Receive the key
  ansible.builtin.command: gpg --debug-level 9 --recv-keys --keyserver hkp://keyserver.ubuntu.com FBA220DFC880C036

- name: Locally sign the key
  ansible.builtin.command: pacman-key --lsign-key F05E8C12131AEB5E

- name: reflector - install
  community.general.pacman:
    name: reflector
    state: present
    update_cache: yes

- name: reflector - run
  ansible.builtin.command: reflector --verbose --latest 5 --sort rate --save /etc/pacman.d/mirrorlist
