- name: virtualbox-guest-utils-nox
  community.general.pacman:
    name: virtualbox-guest-utils-nox
    state: absent
    extra_args: --recursive

- name: Find file owner
  ansible.builtin.command:
    cmd: pacman -Qo /usr/bin/VBoxClient
