version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'a2f0'
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'a2f0'
