- hosts: all
  vars:
    dotfiles_dir: ~/dotfiles
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - import_tasks: tasks/arch-linux/reflector.yaml
      become: yes
    - import_tasks: tasks/arch-linux/install-xorg-packages.yaml
      become: yes
    - import_tasks: tasks/arch-linux/install-console-packages.yaml
      become: yes
    - import_tasks: tasks/clone-dotfiles-into-home.yaml
    - import_tasks: tasks/files.yaml
      tags:
         - files
    - import_tasks: tasks/arch-linux/files.yaml
      tags:
         - files
    - import_tasks: tasks/arch-linux/users.yaml
      become: yes
    - import_tasks: tasks/mcabber.yaml
      tags:
        - files
    - import_tasks: tasks/clone-anduril-into-home.yaml
