---
- hosts: all
  tasks:
    - include: tasks/files.yaml
      tags:
         - files
    - include: tasks/arch-linux/files.yaml
      tags:
         - files
    - include: tasks/arch-linux/update-pacman-database.yaml
      become: yes
    - include: tasks/arch-linux/install-xorg-server.yaml
      become: yes
    - include: tasks/arch-linux/install-xorg-packages.yaml
      become: yes
    - include: tasks/arch-linux/install-console-packages.yaml
      become: yes
