- hosts: 127.0.0.1
  connection: local
  become: no
  tasks:
    - include: tasks/files.yaml
      tags:
         - files
    - include: tasks/arch-linux/files.yaml
      tags:
         - files

- hosts: all
  tasks:
    - include: tasks/arch-linux/update-pacman-database.yaml
      become: yes
    - include: tasks/arch-linux/uninstall-default-vagrant-packages.yaml
      become: yes
    - include: tasks/arch-linux/install-xorg-virtualbox-guest-utils.yaml
      become: yes
    - include: tasks/arch-linux/install-xorg-server.yaml
      become: yes
    - include: tasks/arch-linux/install-xorg-packages.yaml
      become: yes
    - include: tasks/arch-linux/install-console-packages.yaml
      become: yes
