---
- hosts: 127.0.0.1
  connection: local
  become: no
  tasks:
    - include: tasks/files.yaml
      tags:
         - files
    - include: tasks/install-homebrew.yaml
    - include: tasks/install-homebrew-packages.yaml
