- hosts: all
  vars:
    dotfiles_dir: ~/dotfiles
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
  - name: Ensure this playbook only runs on Arch Linux
    fail:
      msg: "This playbook is intended for Arch Linux systems only"
    when: ansible_facts['os_family'] not in ['Archlinux']
    tags:
      - always
  tasks:
    - import_tasks: tasks/copy-ssh-keys-from-host-to-guest.yaml
    - import_tasks: tasks/arch-linux/update-pacman-database.yaml
      become: yes
    - import_tasks: tasks/arch-linux/reflector.yaml
      become: yes
    - import_tasks: tasks/arch-linux/update-pacman-database.yaml
      become: yes
    - import_tasks: tasks/arch-linux/update-the-entire-system.yaml
      become: yes
    - import_tasks: tasks/arch-linux/reboot.yaml
      become: yes
    - import_tasks: tasks/arch-linux/uninstall-default-vagrant-packages.yaml
      become: yes
    - import_tasks: tasks/arch-linux/install-xorg-virtualbox-guest-utils.yaml
      become: yes
