- name: ~/.vimrc
  file:
    src: "{{playbook_dir}}/files/vimrc"
    dest: ~/.vimrc
    state: link

- name: ~/Library/ApplicationSupport/Code/User/settings.json
  file:
    src: "{{playbook_dir}}/files/visual-studio-code-settings.json"
    dest: ~/Library/ApplicationSupport/Code/User/settings.json
    state: link