- name: ~/.aspell.en.pws
  file:
    src: "{{playbook_dir}}/files/aspell.en.pws"
    dest: ~/.aspell.en.pws
    state: link
    force: yes

- name: ~/.inputrc
  file:
    src: "{{playbook_dir}}/files/inputrc"
    dest: ~/.inputrc
    state: link
    force: yes

- name: ~/.profile
  file:
    src: "{{playbook_dir}}/files/profile"
    dest: ~/.profile
    state: link
    force: yes

- name: ~/.mailcap
  file:
    src: "{{playbook_dir}}/files/mailcap"
    dest: ~/.mailcap
    state: link
    force: yes

- name: ~/.vimrc
  file:
    src: "{{playbook_dir}}/files/vimrc"
    dest: ~/.vimrc
    state: link
    force: yes

- name: ~/Library/ApplicationSupport/Code/User/settings.json
  file:
    src: "{{playbook_dir}}/files/visual-studio-code-settings.json"
    dest: ~/Library/ApplicationSupport/Code/User/settings.json
    state: link
    force: yes

