- name: make sure ~/go exists
  file:
    path: ~/go
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0700

- name: make sure ~/go/bin exists
  file:
    path: ~/go/bin
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0700
