- name: azure-cli
  homebrew:
    name: azure-cli
    state: present

- name: bitchx
  homebrew:
    name: bitchx
    state: present

- name: bfg
  homebrew:
    name: bfg
    state: present

- name: dos2unix
  homebrew:
    name: dos2unix
    state: present

- name: gcc
  homebrew:
    name: gcc
    state: present

- name: git # for gitk
  homebrew:
    name: git
    state: present

- name: imagemagick
  homebrew:
    name: vim
    state: present

- name: jenv
  homebrew:
    name: jenv
    state: present

- name: jq
  homebrew:
    name: jq
    state: present

- name: kubernetes-helm
  homebrew:
    name: kubernetes-helm
    state: present

- name: mitmproxy
  homebrew:
    name: mitmproxy
    state: present

- name: nmap
  homebrew:
    name: nmap
    state: present

- name: packer
  homebrew:
    name: packer
    state: present

- name: postgresql
  homebrew:
    name: postgresql
    state: present

- name: pre-commit
  homebrew:
    name: pre-commit
    state: present

- name: tflint
  homebrew:
    name: tflint
    state: present

- name: watchman
  homebrew:
    name: watchman
    state: present

- name: wget
  homebrew:
    name: wget
    state: present

- name: rbenv
  homebrew:
    name: rbenv
    state: present

- name: telnet
  homebrew:
    name: telnet
    state: present

- name: vim
  homebrew:
    name: vim
    state: present

- name: epic5
  homebrew:
    name: epic5
    state: present

- name: pyenv
  homebrew:
    name: pyenv
    state: present

- name: zlib
  homebrew:
    name: zlib
    state: present

- name: bzip2
  homebrew:
    name: bzip2
    state: present

- name: shellcheck
  homebrew:
    name: shellcheck
    state: present

- name: youtube-dl
  homebrew:
    name: youtube-dl
    state: present
