- name: make sure ~/.mcabber exists
  file:
    path: ~/.mcabber
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0700

- name: make sure ~/.mcabber/otr exists
  file:
    path: ~/.mcabber/otr
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0700
