#!/bin/sh
alias epoch="date +%s"
alias listrunning="vboxmanage list runningvms"
alias listvms="vboxmanage list vms"
alias lscreen="screen -ls"
alias mscreen="screen -S mail -c ~/.mscreenrc"
alias npatch="npm version patch --git-tag-version=false"
alias offlineimap="offlineimap -c ~/.offlineimaprc"
alias showrunning="vboxmanage list runningvms"
alias showvminfo="vboxmanage metrics list"
alias branches="git branches"
alias vi="nvim"
alias vim="nvim"
alias adbize="adb devices | tail -n +2 | cut -f1 | xargs -I {} adb -s {} reverse tcp:3000 tcp:3000"
alias unlockagent="echo 'test' | gpg --sign --default-key 6FFAEA28B304FA98E7521822827B8379F39A31F0 > /dev/null"
alias pn="pnpm"

if [ "$(uname -n)" = x1 ]; then
    # copy whatever was selected into the actual clipboard
    alias clipboard="xclip -out | xclip -selection clipboard"
    alias currentbranch="git branch --show-current | tr -d '\n' | xclip -selection clipboard"
    alias lock="xlock -mode laser"
    alias windows="xwininfo -root -children"
fi

if [ "$(uname)" = Darwin ]; then
    alias derived="rm -rf ~/Library/Developer/Xcode/DerivedData"
    alias lsusb="system_profiler SPUSBDataType"
    alias md5sum="md5"
    alias resetwireless="sudo ifconfig en0 down;sudo ifconfig en0 up"
    alias lock='open -a /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app'
    alias currentbranch="git branch --show-current | tee /dev/tty | tr -d '\n' | pbcopy"
    alias derived="rm -rf ~/Library/Developer/Xcode/DerivedData"
fi
