#!/bin/sh

# delete other branches
dlob () {
    git remote prune origin
    git branch | grep -v "$(git branch --show-current)" | xargs git branch -D
}

rip () {
    yt-dlp --extract-audio --audio-format mp3 "$1" --add-metadata "$1" --embed-thumbnail
}

ide () {
    tmux new-session -d nvim
    tmux split-window -v
    tmux split-window -h
    tmux select-layout main-horizontal
    tmux select-pane -t 0
    tmux attach-session -d
}

# To reattach: tmux attach
tearleads () {
    tmux new-session -d -c "$HOME/github/rapid" -n rapid
    tmux new-window -c "$HOME/github/rapid2" -n rapid2
    tmux new-window -c "$HOME/github/rapid3" -n rapid3
    tmux new-window -c "$HOME/github/rapid4" -n rapid4
    tmux new-window -c "$HOME/github/rapid5" -n rapid5
    tmux new-window -c "$HOME/github/rapid6" -n rapid6
    tmux new-window -c "$HOME/github/rapid7" -n rapid7
    tmux new-window -c "$HOME/github/rapid8" -n rapid8
    tmux new-window -c "$HOME/github/rapid9" -n rapid9
    tmux new-window -c "$HOME/github/rapid10" -n rapid10
    tmux new-window -c "$HOME/github/rapid11" -n rapid11
    tmux select-window -t 0
    tmux attach-session -d
}

killport () {
    if ! lsof -i :"$1" >/dev/null 2>&1; then
        echo "No process found listening on port $1"
        return 0
    fi
    lsof -i :"$1" | awk 'NR>1 {print $2}' | xargs kill -9
}
