#!/bin/sh

# delete other branches
dlob () {
    git remote prune origin
    git branch | grep -v "$(git branch --show-current)" | xargs git branch -D
}

rip () {
    yt-dlp --extract-audio --audio-format mp3 "$1" --add-metadata "$1"
}

ide () {
    tmux new-session -d
    tmux split-window -h
    tmux split-window -v
    tmux new-window
    tmux attach-session -d
}
