---
- name: Make sure ~/.config/weechat exists
  ansible.builtin.file:
    path: "{{ dotfiles_home | default(ansible_facts['user_dir']) }}/.config/weechat"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    mode: "0700"
