#!/bin/bash

# unset all aliases
unalias -a

# re-source aliases
[ -e ~/.aliases ] && source ~/.aliases
[ -e ~/.aliases-private ] && source ~/.aliases-private
[ -e ~/.functions ] && source ~/.functions
[ -e ~/.quick ] && source ~/.quick

# unset all functions
for function in `declare -F | awk '{ print $3 }' `; do unset -f  "$function"; done

[ -e ~/.functions ] && source ~/.functions
[ -e ~/.functions-posix ] && source ~/.functions-posix
[ -e ~/.functions-private ] && source ~/.functions-private

# enable vi mode (set +o vi to revert)
set -o vi

# set the editor
export EDITOR="vim"

# set the umask to prevent files from being created with access
# to group members or others
umask 0077

# Avoid duplicate PATH entries to keep PATH deterministic and reduce shadowing risks.
path_prepend() {
    case ":$PATH:" in
        *":$1:"*) return ;;
        *) PATH="$1${PATH:+:${PATH}}" ;;
    esac
}

path_append() {
    case ":$PATH:" in
        *":$1:"*) return ;;
        *) PATH="${PATH:+${PATH}:}$1" ;;
    esac
}

export PATH

# custom compiled software (./configure --prefix=~/install)
path_append "~/install/bin"

# from ~/.functions
bash_prompt

# also see efnet/freenode functions in ~/.functions
export IRCSERVER="irc.servercentral.net 9999 IRC-SSL"
export IRCNICK="dps"
export IRCNAME="dps"

# enable timestamp on bash_history
export HISTTIMEFORMAT="%d.%m.%y %T "
# exempt commands that start with spaces from ~/.bash_history
export HISTCONTROL=ignorespace

# pyenv, installed via brew
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || path_prepend "$PYENV_ROOT/bin"
eval "$(pyenv init -)"

# use UTF-8 - Ansible requires this.
export LC_ALL=en_US.UTF-8

# jenv, installed via git
# make sure to run 'jenv enable-plugin export' after installing to enable the JAVA_HOME export.
path_prepend "$HOME/.jenv/bin"
eval "$(jenv init -)"

# rbenv installed via git
eval "$(~/.rbenv/bin/rbenv init - bash)"

if [ `uname` == Darwin ]; then
    # suppress deprecation warning
    export BASH_SILENCE_DEPRECATION_WARNING=1

    # don't use GitHub's personal access token for features such as brew search
    export HOMEBREW_NO_GITHUB_API=1

    # use UTF-8.
    export LC_ALL=en_US.UTF-8

    # android studio
    export ANDROID_HOME="$HOME/Library/Android/sdk"
    export ANDROID_SDK="$ANDROID_HOME"
    export ANDROID_SDK_ROOT="$ANDROID_HOME"
    path_append "$ANDROID_HOME/cmdline-tools/latest/bin"
    path_append "$ANDROID_HOME/emulator"
    path_append "$ANDROID_HOME/platform-tools"

    # go, installed via brew
    export GOPATH="$HOME/go"
    path_append "${GOPATH}/bin"

    # az cli, installed via brew
    source /opt/homebrew/etc/bash_completion.d/az

    # fastlane
    path_append "$HOME/.fastlane/bin"

    # gcloud
    if [ -f "$HOME/google-cloud-sdk/path.bash.inc" ]; then . "$HOME/google-cloud-sdk/path.bash.inc"; fi
    if [ -f "$HOME/google-cloud-sdk/completion.bash.inc" ]; then . "$HOME/google-cloud-sdk/path.bash.inc"; fi

    # nvm, installed via brew
    export NVM_DIR="$HOME/.nvm"
    [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && . "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
    [ -s "/opt/homebrew/opt/nvm/etc/bash_completion" ] && . "/opt/homebrew/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

    # for git gpg signature verification
    export GPG_TTY=$(tty)

elif [ `uname -n` == x1 ]; then
    path_append "~/.cabal/bin"

    # vendor perl, for perlbrew
    path_append "/usr/bin/vendor_perl"

    # X Desktop Group Configuration Paths
    export XDG_CONFIG_HOME="$HOME/.config"
    export XDG_CACHE_HOME="$HOME/.cache"

    # android studio
    export ANDROID_HOME="$HOME/Android/Sdk"
    export ANDROID_SDK="$ANDROID_HOME"
    export ANDROID_SDK_ROOT="$ANDROID_HOME"
    path_append "$ANDROID_HOME/cmdline-tools/latest/bin"
    path_append "$ANDROID_HOME/emulator"
    path_append "$ANDROID_HOME/platform-tools"

    # fastboot, lineageos
    path_append "$HOME/platform-tools"

    # dotfiles scripts
    path_append "$HOME/dotfiles/files/shellcheck"

    # rust installed using rustup
    . "$HOME/.cargo/env"

    # terraform virtual environment installed manually
    path_prepend "$HOME/.tfenv/bin"

    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi
