# unset all aliases
unalias -a

# re-source aliases
[ -e ~/.aliases ] && source ~/.aliases
[ -e ~/.aliases-private ] && source ~/.aliases-private
[ -e ~/.functions ] && source ~/.functions
[ -e ~/.quick ] && source ~/.quick

# unset all functions
for function in `declare -F | awk '{ print $3 }' `; do unset -f  "$function"; done

[ -e ~/.functions ] && source ~/.functions
[ -e ~/.functions-private ] && source ~/.functions-private

# ~/.functions
trap ctrl_c INT
trap hangup HUP
trap hangup KILL

# enable vi mode (set +o vi to revert)
set -o vi

# set the editor
export EDITOR="vim"

# enable timestamp on bash_history
export HISTTIMEFORMAT="%d.%m.%y %T "

# set the umask to prevent files from being created with access
# to group members or others
umask 0077

# custom compiled software (./configure --prefix=~/install)
PATH=$PATH:~/install/bin

if [ `uname` == Darwin ]; then
    # suppress deprecation warning
    export BASH_SILENCE_DEPRECATION_WARNING=1

    # don't use GitHub's personal access token for features such as brew search
    export HOMEBREW_NO_GITHUB_API=1

    # use UTF-8.
    export LC_ALL=en_US.UTF-8

    # android development
    export ANDROID_SDK=$HOME/Library/Android/sdk
    export JAVA_HOME=`/usr/libexec/java_home -v 1.6`

    # go, installed via brew
    export GOPATH=$HOME/go
    export PATH="$PATH:${GOPATH}/bin"

    # az cli, installed via brew
    source /usr/local/etc/bash_completion.d/az

    # fastlane
    export PATH="$HOME/.fastlane/bin:$PATH"

    # gcloud
    if [ -f "$HOME/google-cloud-sdk/path.bash.inc" ]; then . "$HOME/google-cloud-sdk/path.bash.inc"; fi
    if [ -f "$HOME/google-cloud-sdk/completion.bash.inc" ]; then . "$HOME/google-cloud-sdk/path.bash.inc"; fi

    # nvm, installed via brew
    export NVM_DIR="$HOME/.nvm"
    [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
    [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion
    alias cd='cdnvm'

    # for git gpg signature verification
    export GPG_TTY=$(tty)

elif [ `uname` == Linux ]; then
    # init volume to 20.
    #amixer sset Master 67%
    PATH=$PATH:/opt/local/scripts
    PATH=$PATH:~/.cabal/bin
    PATH=$PATH:/usr/local/heroku/bin
    # vendor perl, for perlbrew
    PATH=$PATH:/usr/bin/vendor_perl
    # disable terminal beep
    # setterm -blength 0
    # X Desktop Group Configuration Paths
    export XDG_CONFIG_HOME=$HOME/.config
    export XDG_CACHE_HOME=$HOME/.cache
    # use the default POSIX/C locale, print only standard ASCII characters.
    export LC_ALL=C
    export JAVA_HOME=/opt/local/jdk1.7.0_45
fi

# from ~/.functions
bash_prompt
loadrbenv

# also see efnet/freenode functions in ~/.functions
export IRCSERVER="irc.servercentral.net 9999 IRC-SSL"
export IRCNICK="dps"
export IRCNAME="dps"

# set cvs remote shell
export CVS_RSH=ssh

# exempt commands that start with spaces from ~/.bash_history
export HISTCONTROL=ignorespace

# Use bash completion, if it exists - linux.cs.uchicago.edu
[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && \
    . /usr/share/bash-completion/bash_completion
