#!/bin/bash

# unset all aliases
unalias -a

# re-source aliases
[ -e ~/.aliases ] && source ~/.aliases
[ -e ~/.aliases-private ] && source ~/.aliases-private
[ -e ~/.functions ] && source ~/.functions
[ -e ~/.quick ] && source ~/.quick

# unset all functions
for function in `declare -F | awk '{ print $3 }' `; do unset -f  "$function"; done

[ -e ~/.functions ] && source ~/.functions
[ -e ~/.functions-posix ] && source ~/.functions-posix
[ -e ~/.functions-private ] && source ~/.functions-private

# enable vi mode (set +o vi to revert)
set -o vi

# set the editor
export EDITOR="vim"

# set the umask to prevent files from being created with access
# to group members or others
umask 0077

# custom compiled software (./configure --prefix=~/install)
export PATH=$PATH:~/install/bin

# from ~/.functions
bash_prompt

# also see efnet/freenode functions in ~/.functions
export IRCSERVER="irc.servercentral.net 9999 IRC-SSL"
export IRCNICK="dps"
export IRCNAME="dps"

# enable timestamp on bash_history
export HISTTIMEFORMAT="%d.%m.%y %T "
# exempt commands that start with spaces from ~/.bash_history
export HISTCONTROL=ignorespace

# pyenv, installed via brew
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# use UTF-8 - Ansible requires this.
export LC_ALL=en_US.UTF-8

# jenv, installed via git
# make sure to run 'jenv enable-plugin export' after installing to enable the JAVA_HOME export.
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# rbenv installed via git
eval "$(~/.rbenv/bin/rbenv init - bash)"

if [ `uname` == Darwin ]; then
    # suppress deprecation warning
    export BASH_SILENCE_DEPRECATION_WARNING=1

    # don't use GitHub's personal access token for features such as brew search
    export HOMEBREW_NO_GITHUB_API=1

    # use UTF-8.
    export LC_ALL=en_US.UTF-8

    # android studio
    export ANDROID_SDK=$HOME/Library/Android/sdk
    export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
    export ANDROID_HOME=$HOME/Library/Android/sdk
    export PATH=$PATH:$HOME/Library/Android/sdk/cmdline-tools/latest/bin
    export PATH=$PATH:$HOME/Library/Android/sdk/emulator
    export PATH=$PATH:$HOME/Library/Android/sdk/platform-tools

    # go, installed via brew
    export GOPATH=$HOME/go
    export PATH="$PATH:${GOPATH}/bin"

    # az cli, installed via brew
    source /usr/local/etc/bash_completion.d/az

    # fastlane
    export PATH="$HOME/.fastlane/bin:$PATH"

    # gcloud
    if [ -f "$HOME/google-cloud-sdk/path.bash.inc" ]; then . "$HOME/google-cloud-sdk/path.bash.inc"; fi
    if [ -f "$HOME/google-cloud-sdk/completion.bash.inc" ]; then . "$HOME/google-cloud-sdk/path.bash.inc"; fi

    # nvm, installed via brew
    export NVM_DIR="$HOME/.nvm"
    [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
    [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

    # for git gpg signature verification
    export GPG_TTY=$(tty)

elif [ `uname -n` == x1 ]; then
    PATH=$PATH:~/.cabal/bin

    # vendor perl, for perlbrew
    PATH=$PATH:/usr/bin/vendor_perl

    # X Desktop Group Configuration Paths
    export XDG_CONFIG_HOME=$HOME/.config
    export XDG_CACHE_HOME=$HOME/.cache

    # android studio
    export ANDROID_SDK=$HOME/Android/Sdk
    export ANDROID_SDK_ROOT=$HOME/Android/Sdk
    export ANDROID_HOME=$HOME/Android/Sdk
    export PATH=$PATH:$HOME/Android/Sdk/cmdline-tools/latest/bin
    export PATH=$PATH:$HOME/Android/Sdk/emulator
    export PATH=$PATH:$HOME/Android/Sdk/platform-tools

    # fastboot, lineageos
    export PATH=$PATH:$HOME/platform-tools

    # dotfiles scripts
    export PATH=$PATH:$HOME/dotfiles/files/shellcheck

    # rust installed using rustup
    . "$HOME/.cargo/env"

    # terraform virtual environment installed manually
    export PATH="$HOME/.tfenv/bin:$PATH"

    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi
