# keep the clipboard in sync with the primary buffer
autocutsel -selection CLIPBOARD -fork

# keep the primary in sync with the clipboard buffer
autocutsel -selection PRIMARY -fork

# disable power saving of capabilities of monitors (when not in use)
xset -dpms

# disable the screen saver function
xset s off

# change the pointer cursor
xsetroot -cursor_name -left_ptr

# set the audible beep for X11
xset -b

# set the mouse tracking speed to fast
xset m 100 1

# set the keyboard delay and repeat rate
xset r rate 200 100

# load ~/.Xresources
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

#exec xmonad
exec startxfce4
