source ~/.aliases
source ~/.aliases-private
source ~/.functions-posix
source ~/.functions-zsh
source ~/.quick

# set the umask to prevent files from being created with access
# to group members or others
umask 0077

# gcloud
if [ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/google-cloud-sdk/path.zsh.inc"; fi
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/google-cloud-sdk/path.zsh.inc"; fi

if [[ `uname` == Darwin ]]; then

  # brew
  eval "$(/opt/homebrew/bin/brew shellenv)"

  # rbenv - installed via brew
  if hash rbenv 2>/dev/null; then
    eval "$(rbenv init -)"
  fi

  # pyenv - installed via brew
  if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
  fi

  # jenv - installed via brew
  eval "$(jenv init -)"

  # nvm - installed via brew
  export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

  # android studio
  export ANDROID_SDK=$HOME/Library/Android/sdk
  export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
  export PATH=$PATH:$HOME/Library/Android/sdk/tools/bin
  export PATH=$PATH:$HOME/Library/Android/sdk/emulator
  export PATH=$PATH:$HOME/Library/Android/sdk/platform-tools
  export PATH=$PATH:$HOME/Library/Android/sdk/build-tools/30.0.3

  # go - installed via brew
  export GOPATH=$HOME/go
  export PATH="$PATH:${GOPATH}/bin"

  # for git gpg signature verification
  export GPG_TTY=$(tty)
fi

alias vi="nvim"
alias vim="nvim"

# platform independent aliases
alias branches="git branches"

# set the locale
export LC_ALL=en_US.UTF-8

# aws cli tools
export AWS_PAGER="" # disable the use of a pager

# custom compiled software (./configure --prefix=~/install, export PREFIX=~/install, etc.)
export PATH=$PATH:~/install/bin

# dotfiles scripts
export PATH=$PATH:$HOME/dotfiles/files/shellcheck

# also see efnet/freenode functions in ~/.functions
export IRCSERVER="irc.servercentral.net 9999 IRC-SSL"
export IRCNICK="dps"
export IRCNAME="dps"

# antigen, installed via curl
source ~/install/bin/antigen.zsh
antigen use oh-my-zsh
antigen theme robbyrussell
antigen bundle vi-mode
export NVM_AUTO_USE=true
antigen bundle lukechilds/zsh-nvm
antigen apply

# history settings
HISTSIZE=1000               # how many lines of history to keep in memory
HISTFILE=~/.zsh_history     # where to save history to disk
SAVEHIST=1000               # number of history entries to save to disk
setopt no_share_history     # don't share history across terminals
unsetopt share_history      # don't share history across terminals
alias history="history 1"   # display all entries from entry number 1

export EDITOR="nvim"
