---
- name: Make sure directories exist
  ansible.builtin.file:
    path: "{{ dotfiles_home | default(ansible_facts['user_dir']) }}/{{ item }}"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    mode: "0700"
  loop:
    - 'Library/Preferences/'
    - 'Library/Application Support/Code/User/'
    - 'Library/Application Support/Cursor/User/'
    - 'Library/Application Support/Antigravity/User/'
    - 'Library/Application Support/com.mitchellh.ghostty/'

- name: Create symlinks
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/files/{{ item.src }}"
    dest: "{{ dotfiles_home | default(ansible_facts['user_dir']) }}/{{ item.dest }}"
    state: link
    force: false
    follow: false
  loop:
    - { src: 'visual-studio-code-settings.json', dest: 'Library/Application Support/Code/User/settings.json' }
    - { src: 'cursor-settings.json', dest: 'Library/Application Support/Cursor/User/settings.json' }
    - { src: 'antigravity-settings.json', dest: 'Library/Application Support/Antigravity/User/settings.json' }
    - { src: 'com.mitchellh.ghostty.config', dest: 'Library/Application Support/com.mitchellh.ghostty/config' }

- name: Create symlinks for terminal preferences
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/files/{{ item }}"
    dest: "{{ dotfiles_home | default(ansible_facts['user_dir']) }}/Library/Preferences/{{ item }}"
    state: link
    force: false
    follow: false
  loop:
    - com.googlecode.iterm2.plist
    - com.apple.Terminal.plist
