- name: ~/Library/ApplicationSupport/Code/User/settings.json
  file:
    src: "{{dotfiles_dir}}/files/visual-studio-code-settings.json"
    dest: ~/Library/ApplicationSupport/Code/User/settings.json
    state: link
    force: yes
