- name: ensure homebrew is updated
  homebrew:
    state: latest
    update_homebrew: yes

- name: tap heroku
  community.general.homebrew_tap:
    name: heroku/brew

- name: Install libraries with homebrew
  homebrew: name={{ item }} state=present
  with_items:
    - act
    - aspell
    - azure-cli
    - bfg
    - bitchx
    - bitwarden-cli
    - bzip2
    - dos2unix
    - epic5
    - foreman
    - gcc
    - gh
    - git
    - golang
    - haskell-stack
    - heroku
    - imagemagick
    - imapfilter
    - jenv
    - jq
    - kubernetes-helm
    - mitmproxy
    - mutt
    - nmap
    - nvm
    - offlineimap
    - packer
    - postgresql
    - pre-commit
    - pyenv
    - rbenv
    - rust
    - shellcheck
    - telnet
    - tfenv
    - tflint
    - vim
    - watchman
    - wget
    - youtube-dl
    - zlib
