name: Github Actions

on:
  push:
    branches: '**'
jobs:
  code-quality:
    runs-on: macos-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.13'
        architecture: 'x64'
    - name: install shellcheck and luacheck
      run: |
        brew install shellcheck
        brew install luacheck
    - name: install and configure python dependencies
      run: pip install -r ./requirements.txt
    - name: Run pre-commit
      run: |
        pre-commit install
        pre-commit autoupdate
        pre-commit run --all-files
      env:
          SKIP: no-commit-to-branch
    - name: Run ansible MacOS
      run: ./runAnsible.sh

  ansible-ubuntu:
    runs-on: ubuntu-24.04
    continue-on-error: false
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.13'
        architecture: 'x64'
    - name: install and configure python dependencies
      run: pip install -r ./requirements.txt
    - name: Run ansible Ubuntu 24.04
      run: ./runAnsible.sh -e "dotfiles_dir=${GITHUB_WORKSPACE} clone_dotfiles=false"
